In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/accounts.csv")
df.head()

print(df.info())
print(df.describe())
print(df.isnull().sum())

categorical_cols = ['account_type', 'status']
le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
df.drop(columns=['account_id', 'customer_id', 'branch_id', 'open_date'], inplace=True)

scaler = StandardScaler()
numerical_cols = ['balance']
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

X = df.drop('status', axis=1)
y = df['status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Data Shape:", X_train.shape)
print("Test Data Shape:", X_test.shape)
X_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95000 entries, 0 to 94999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    95000 non-null  int64
 1   customer_id   95000 non-null  int64
 2   branch_id     95000 non-null  int64
 3   account_type  95000 non-null  object
 4   balance       95000 non-null  float64
 5   open_date     95000 non-null  object
 6   status        95000 non-null  object
dtypes: float64(1), int64(3), object(3)
memory usage: 5.1+ MB
None
         account_id   customer_id     branch_id        balance
count  95000.000000  95000.000000  95000.000000   95000.000000
mean   47500.500000  29991.208179     75.450695   45761.236422
std    27424.282124  17264.584944     43.295402   45306.411751
min        1.000000      1.000000      1.000000     500.360000
25%    23750.750000  15114.750000     38.000000   13551.047500
50%    47500.500000  30000.000000     75.000000   31768.655000
75%    71250.250000  44910.000000    113.000000   63337.515000
max    95000.000000  60000.000000    150.000000  539198.590000
account_id      0
customer_id     0
branch_id       0
account_type    0
balance         0
open_date       0
status          0
dtype: int64
Training Data Shape: (76000, 2)
Test Data Shape: (19000, 2)

       account_type   balance
77756             0  0.220761
90555             0  0.885584
34919             4 -0.992641
30594             1 -0.919957
8188              2 -0.953150

In [5]:
!pip install numpy pandas matplotlib seaborn scikit-learn

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/accounts.csv")
df.head()

print(df.info())
print(df.describe())
print(df.isnull().sum())

categorical_cols = ['account_type', 'status']
le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
df.drop(columns=['account_id', 'customer_id', 'branch_id', 'open_date'], inplace=True)

scaler = StandardScaler()
numerical_cols = ['balance']
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

X = df.drop('status', axis=1)
y = df['status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Data Shape:", X_train.shape)
print("Test Data Shape:", X_test.shape)
X_train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95000 entries, 0 to 94999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    95000 non-null  int64
 1   customer_id   95000 non-null  int64
 2   branch_id     95000 non-null  int64
 3   account_type  95000 non-null  object
 4   balance       95000 non-null  float64
 5   open_date     95000 non-null  object
 6   status        95000 non-null  object
dtypes: float64(1), int64(3), object(3)
memory usage: 5.1+ MB
None
         account_id   customer_id     branch_id        balance
count  95000.000000  95000.000000  95000.000000   95000.000000
mean   47500.500000  29991.208179     75.450695   45761.236422
std    27424.282124  17264.584944     43.295402   45306.411751
min        1.000000      1.000000      1.000000     500.360000
25%    23750.750000  15114.750000     38.000000   13551.047500
50%    47500.500000  30000.000000     75.000000   31768.655000
75%    71250.250000  44910.000000    113.000000   63337.515000
max    95000.000000  60000.000000    150.000000  539198.590000
account_id      0
customer_id     0
branch_id       0
account_type    0
balance         0
open_date       0
status          0
dtype: int64
Training Data Shape: (76000, 2)
Test Data Shape: (19000, 2)

       account_type   balance
77756             0  0.220761
90555             0  0.885584
34919             4 -0.992641
30594             1 -0.919957
8188              2 -0.953150